Added branch param to gbdel

diff --git a/gbdel b/gbdel
--- a/gbdel
+++ b/gbdel
@@ -1,4 +1,30 @@
 #!/bin/bash
 
-git push origin --delete $(git branch | grep "$1")
-git branch -D $(git branch | grep "$1")
+if [[ -z "$1" ]]; then
+	echo "Branch parameter is required. Add branch name as argument or -a to remove all merged branches."
+	exit 1
+fi
+
+if [[ "$1" == "-a" ]]; then
+	branches=$(git b -a --merged | grep -E "origin/feature|origin/bugfix" | cut -d '/' -f 3-)
+
+	echo -n "The following branches will be deleted from ORIGIN:"
+	echo ""
+	echo "$branches"
+	echo ""
+	echo "To confirm insert (y/n):"
+	echo ""
+	read confirm
+
+	confirm=${confirm:-y}
+
+	if [[ $confirm == "y" || $confirm == "yes" ]]; then
+		for branch in $branches; do
+			git push origin --delete "$branch"
+			git branch -D "$branch"
+		done
+	fi
+else
+	git push origin --delete $(git branch | grep "$1")
+	git branch -D $(git branch | grep "$1")
+fi
